import React from 'react'
import Header from '@/components/Header'
import type { Metadata } from "next";

const NotFound = () => (
  <section className="w-full bg-white">
    <Header title="404 Error" link="404" />
    <div className="bg-white w-full min-h-[550px] flex items-center justify-center py-6">
      <div className="w-full max-w-[630px] min-h-[342px] h-auto flex flex-col items-center justify-between text-center px-4">
        <h1 className="font-bold text-8xl text-[var(--primary-yellow)]">404</h1>
        <h4 className="font-bold sm:text-2xl text-xl text-[#333333]">Oops! Looks like something went wrong</h4>
        <p className="w-full max-w-[490px] text-base sm:text-lg text-[#4F4F4F] mt-2">
          Page cannot be found! We&#39;ll have it figured out in no time.
          Meanwhile, check out these fresh ideas:
        </p>
        <button className="w-[197px] h-[58px] mt-4 rounded-md bg-[var(--primary-yellow)] text-white text-base sm:text-lg font-bold py-4 px-12">
          Go to home
        </button>
      </div>
    </div>
  </section>


)

export const metadata: Metadata = {
  title: "404: This page not found",
  description: "Generated by create next app",
};

export default NotFound